### ISSUE TITLE
Several cast errors in MinGW x64 4.8.1

### ISSUE THREAD

**Issue by arietto** [seladb/PcapPlusPlus#39]
Hello! I can't compile in MinGW x64 4.8.1, because the file Common/src/debug_new.cpp contains the error
debug_new.cpp:30:46: error: cast from 'void*' to 'long unsigned int' loses precision [-fpermissive]
 #define DEBUG_NEW_HASH(p) (((unsigned long)(p) >> 8) % DEBUG_NEW_HASHTABLESIZE)
Also there are some other cast errors
src/PcapFilter.cpp:113:35: error: cast from 'uint8_t* {aka unsigned char*}' to 'long int' loses precision 
uint64_t addrLowerBytes = (long)addrAsArr;
src/PcapFilter.cpp:114:48: error: cast from 'uint8_t* {aka unsigned char*}' to 'long int' loses precision 
   uint64_t addrHigherBytes = (long)(addrAsArr+8);

**Comment by seladb** [comment]
MinGW x64 isn't currently supported (only the 32-bit version is working). The main reason (except for these compilation errors which are easy to fix) is that I didn't manage to link my code with the x64 WinPcap libraries. From Googling this issue, I didn't find any working solution so it seems that the only way to link with x64 WinPcap is to re-compile WinPcap with MinGW x64. I didn't get to that yet

**Comment by arietto** [comment]
Readme.md contains the folowing fragment: "It was tested on Windows (32bit and 64bit) with Mingw32 and MingGW-w64". I suppose that you should explicitly mention that MinGW x64 isn't currently supported  in readme.md.

**Comment by seladb** [comment]
MinGW-w64 is a fork of MinGW32. It contains both 32-bit and 64-bit compilers. I will add the comment you suggested, thanks
