### ISSUE TITLE
Error running example app: `IPv4Layer.h: No such file or directory`

### ISSUE THREAD

**Issue by Octalbyte** [seladb/PcapPlusPlus#795]
![image](https://user-images.githubusercontent.com/66487668/151387896-e3fcebf2-1ffb-4d14-80d8-6e45755976cc.png)

I am using:

g++ 11.2.0 (with all the mingw32 toolchain) 
windows 10 (32-bit)
The latest Pcap++ release

I am also running the app from the `example-app` folder.
Is this an issue with linking? I am a bit new to c++

**Comment by seladb** [comment]
@Octalbyte if you look at the files inside the [`pcapplusplus-21.11-windows-mingw32-gcc-9.2.0.zip`](https://github.com/seladb/PcapPlusPlus/releases/download/v21.11/pcapplusplus-21.11-windows-mingw32-gcc-9.2.0.zip) package you'll find `example-app\README.md` and `README.release` which contains details instructions:

`example-app\README.md`:

```text
PcapPlusPlus Example Application
================================

This folder contains the source code and a Makefile of a simple application that uses PcapPlusPlus.

The code is based on the "Hello World" application in PcapPlusPlus Tutorials (https://pcapplusplus.github.io/docs/tutorials/intro#writing-a-simple-app-including-a-makefile).

In order to compile this application please follow the steps in README.release (the part that explains how to compile the application). 
You can skip the step which instructs to include `mk\PcapPlusPlus.mk` in the Makefile - this Makefile already includes this file.
```

`README.release`:

```text
In order to compile your application with these binaries you need to:
---------------------------------------------------------------------

 - Make sure you have MinGW32/MinGW-w64 installed with a gcc/g++ version matching the compiled binaries (for example: `pcapplusplus-21.11-windows-mingw32-gcc-9.2.0.zip` pack might not work well with MinGW32 5.3.0)
 - You may have to put MinGW32/MinGW-w64 directory in your `PATH` environment variable
 - Make sure you have WinPcap, Npcap or Wireshark installed
 - Make sure you have WinPcap or Npcap Developer's pack installed (WinPcap Dev Pack can be downloaded from https://www.winpcap.org/devel.htm, Npcap SDK can be downloaded from https://nmap.org/npcap/#download)
 - Update `mk\PcapPlusPlus.mk` file:
     - Set `PCAPPLUSPLUS_HOME` to the folder where binaries are located
     - Set `MINGW_HOME` to the folder where MinGW/MinGW-w64 is installed
     - Set `PCAP_SDK_HOME` to the folder where WinPcap/Npcap Developer's Pack is installed
 - Include `mk\PcapPlusPlus.mk` in your Makefile and add PcapPlusPlus includes, libs, etc. to your Makefile 
     - You can follow the example under `example-app\`
```

Please let me know if you're running into any issues

**Comment by Octalbyte** [comment]
@seladb  Thanks for the help! For some reason there is no `README.release` in my `example-app` folder. Maybe I accidentally deleted it. Now the library *is* being successfully linked, but i get a huge stream of errors. Please note I replaced my username with `fake username`, but, if this matters, my username has spaces in it.

[errors.txt](https://github.com/seladb/PcapPlusPlus/files/7959245/errors.txt)

**Comment by Octalbyte** [comment]
Most errors have to do with undefined references to mingw features. e.g.: `c:/mingw/include/stdlib.h:586: undefined reference to `__mingw_free'`

**Comment by seladb** [comment]
I think you have [MinGW-w64](https://www.mingw-w64.org/) installed and not [MinGW](https://osdn.net/projects/mingw/). Please try downloading [`pcapplusplus-21.11-windows-mingw-w64-gcc-8.1.0.zip`](https://github.com/seladb/PcapPlusPlus/releases/download/v21.11/pcapplusplus-21.11-windows-mingw-w64-gcc-8.1.0.zip) and see if things work

**Comment by Octalbyte** [comment]
@seladb Now everything is working perfectly 🎉. Thanks for the help and effort. Not every community returns help in less than 3 days.
