### ISSUE TITLE
PcapPlusPlus incompatible with dpdk 17.11

### ISSUE THREAD

**Issue by luigino** [seladb/PcapPlusPlus#90]
```
 src/DpdkDeviceList.cpp: In member function 'void pcpp::DpdkDeviceList::setDpdkLogLevel(pcpp::LoggerPP::LogLevel)':
 src/DpdkDeviceList.cpp:255:3: error: 'rte_set_log_level' was not declared in this scope
    rte_set_log_level(RTE_LOG_NOTICE);
    ^~~~~~~~~~~~~~~~~
 src/DpdkDeviceList.cpp:255:3: note: suggested alternative: 'rte_log_set_level'
    rte_set_log_level(RTE_LOG_NOTICE);
    ^~~~~~~~~~~~~~~~~
    rte_log_set_level
 src/DpdkDeviceList.cpp:257:3: error: 'rte_set_log_level' was not declared in this scope
    rte_set_log_level(RTE_LOG_DEBUG);
    ^~~~~~~~~~~~~~~~~
 src/DpdkDeviceList.cpp:257:3: note: suggested alternative: 'rte_log_set_level'
    rte_set_log_level(RTE_LOG_DEBUG);
    ^~~~~~~~~~~~~~~~~
    rte_log_set_level
 src/DpdkDeviceList.cpp: In member function 'pcpp::LoggerPP::LogLevel pcpp::DpdkDeviceList::getDpdkLogLevel()':
 src/DpdkDeviceList.cpp:262:6: error: 'rte_get_log_level' was not declared in this scope
   if (rte_get_log_level() <= RTE_LOG_NOTICE)
       ^~~~~~~~~~~~~~~~~
 src/DpdkDeviceList.cpp:262:6: note: suggested alternative: 'rte_log_set_level'
   if (rte_get_log_level() <= RTE_LOG_NOTICE)
       ^~~~~~~~~~~~~~~~~
       rte_log_set_level
 src/DpdkDeviceList.cpp:266:1: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
```

I see there are rte_set_log_level() and rte_get_log_level() in the new API, but the prototype for the latter is different and I don't know what it's doing there.

**Comment by echo-Mike** [comment]
It is clearly stated here: http://seladb.github.io/PcapPlusPlus-Doc/dpdk-pf_ring.html
that the latest compatible version of DPDK is 17.02 (better use 16.11).

**Comment by luigino** [comment]
I see. Will wait for future releases then, as I rely on distro-supplied DPDK.

**Comment by seladb** [comment]
It should be an easy fix - just replace `rte_set_log_level()` with `rte_log_set_global_level()` and `rte_get_log_level()` with `rte_log_get_global_level()`. I can do that but then I'll lose DPDK 16.11 LTS support. Maybe I'll do this change once a new LTS version of DPDK is released.
@luigino in the meantime you can fork PcapPlusPlus and do this small change yourself

**Comment by luigino** [comment]
See https://github.com/seladb/PcapPlusPlus/pull/92 .

**Comment by seladb** [comment]
Thanks for the fix! but please notice it doesn't build with 16.11, please see comments inside the PR

**Comment by seladb** [comment]
Thanks for the fix! Closing the issue...
