### ISSUE TITLE
make error with DPDK18.08 and newer

### ISSUE THREAD

**Issue by daniel0720** [seladb/PcapPlusPlus#313]
I download dpdk from github, and checkout v18.08, when i make all of the pcapplusplus, errors occured as follows:
`==> Building target: Pcap++
Building file: src/DpdkDevice.cpp
src/DpdkDevice.cpp: In member function ‘bool pcpp::DpdkDevice::configurePort(uint8_t, uint8_t)’:
src/DpdkDevice.cpp:241:18: error: ‘struct rte_eth_rxmode’ has no member named ‘header_split’
  portConf.rxmode.header_split = DPDK_COFIG_HEADER_SPLIT;
                  ^
src/DpdkDevice.cpp:242:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_ip_checksum’
  portConf.rxmode.hw_ip_checksum = DPDK_COFIG_HW_IP_CHECKSUM;
                  ^
src/DpdkDevice.cpp:243:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_vlan_filter’
  portConf.rxmode.hw_vlan_filter = DPDK_COFIG_HW_VLAN_FILTER;
                  ^
src/DpdkDevice.cpp:244:18: error: ‘struct rte_eth_rxmode’ has no member named ‘jumbo_frame’
  portConf.rxmode.jumbo_frame = DPDK_COFIG_JUMBO_FRAME;
                  ^
src/DpdkDevice.cpp:245:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_strip_crc’
  portConf.rxmode.hw_strip_crc = DPDK_COFIG_HW_STRIP_CRC;
                  ^
Makefile:76: recipe for target 'Obj/DpdkDevice.o' failed
make[1]: *** [Obj/DpdkDevice.o] Error 1
Makefile:88: recipe for target 'libs' failed
make: *** [libs] Error 2
`
I have to checkout dpdk to v18.05 to evade the errors. The DpdkDevice.cpp code indicate the dpdk version < v18.11 would work well, but it's not.

**Comment by seladb** [comment]
I have a few questions:
- Which version of PcapPlusPlus are you using? is it the latest version from `master`?
- Did you try to download DPDK18.08 from the [official web-site](http://core.dpdk.org/download/)?
- Can you please describe how you configure and build DPDK?
- Can you please describe how you configure and build PcapPlusPlus after building DPDK?

**Comment by daniel0720** [comment]
Hello seladb，

- Lastest version of PcapPlusPlus
- I download DPDK from github and checkout to v18.08, and I also download DPDK18.08.1 from official web-site.
-  first make config T=x86_64-native-linuxapp-gcc, then make
- ./configure-linux.sh. according the prompt input the path of PF_RING and DPDK. Then make all

**Comment by seladb** [comment]
Did you try newer versions of DPDK or just 18.08?

I'm asking because you mentioned "make error with DPDK18.08 and newer"

**Comment by daniel0720** [comment]
yes. First time I tried the lastest DPDK, then I found PcapPlusPlus is not complatible with newer than 19.02 in the issue, so I tried 19.02. Same error occured. I also tried 18.11.

**Comment by daniel0720** [comment]
sorry I was wrong. When I use newer DPDK, the error is

grep: /home/daniel/workspace/dpdk//pkg/dpdk.spec: No such file or directory

you can take a look at DpdkDevice.cpp code, what is the line 240 means? because dpdk18.08, the "rte_ethdev.h" doesn't have 'header_split' field in the struct rte_eth_rxmode.

**Comment by seladb** [comment]
I do see the problem. However it does work with DPDK 19.08. Let me look into it and get back to you

**Comment by daniel0720** [comment]
OK， thank you

**Comment by seladb** [comment]
I just verified it does work for DPDK 18.11.5 and 19.08. The problem is only with 18.08. Can you try newer versions of DPDK?

I'll provide a fix for 18.08

**Comment by daniel0720** [comment]
ok. I'll do it later.
But now it works fine with DPDK18.05, and make all success. What I want to do is to run benchmark and compare it with others. The benchmark is from https://github.com/mfontanini/packet-capture-benchmarks, but when I make the benchmarks, an error occurd.
pcapplusplus/benchmark.cpp:6:20: fatal error: Packet.h: No such file or directory
perhaps because the benchmark's code is too old.
Can you help me to fix the error?

**Comment by seladb** [comment]
I just provided a quick fix for DPDK18.08. I made it in `dev` branch to make sure I didn't break anything. I'll merge it to `master` later.

Regarding the benchmark - I didn't write this code so I'm not sure why it's not working. Perhaps you need to install PcapPlusPlus first (using `make install`)?

If you'd like to run a benchmark I'd advise you to run the one I wrote: https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapPlusPlus-benchmark
