### ISSUE TITLE
Cannot build with XDP support against libbpf > 1.0

### ISSUE THREAD

**Issue by cconverse711** [seladb/PcapPlusPlus#2227]
### Bug description

**Describe the bug**
Building with XDP support enabled fails against libbpf > 1.0, since xsk.h was moved from libbpf to libxdp. Originally raised in #1635 

**Code example to reproduce**
```
$ cat /usr/include/bpf/libbpf_version.h | grep "LIBBPF_.*_VERSION"
#define LIBBPF_MAJOR_VERSION 1
#define LIBBPF_MINOR_VERSION 3

$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 24.04.4 LTS"

$ cmake .. -DPCAPPP_USE_XDP=ON
$ make
/home/user/code/PcapPlusPlus/Pcap++/src/XdpDevice.cpp:8:10: fatal error: bpf/xsk.h: No such file or directory
```

**Expected behavior**
Code should compile successfully, with XDP support

### PcapPlusPlus versions tested on

PcapPlusPlus master branch

### Operating systems tested on

Linux

### Compiler version

g++ 13.3.0

### Packet capture backend (if applicable)

XDP

**Comment by seladb** [comment]
Fixed in #2228 . Thank you @cconverse711 for reporting the issue and working on the fix, much appreciated 🙏
